### ISSUE TITLE
Inconsitencies in hight of graph

### ISSUE THREAD

**Issue by klartext** [carlaiau/flatten-the-curve#14]
Spain: 2808 deaths at end of curve
China: 2116 deaths at end of curve
But Chinas graph is much higher than that of spain.
Something is wrong here.

Please also check validit yof the other data, I suspect there might be other problems as well.

**Comment by carlaiau** [comment]
This is because the max days of accumulation is trimmed to 30 (I will adjust this as countries infection progress continues) which presently only effects China, so it is cutting the accumulation short. Without trimming the accumulation all other countries bunch up on the left as the X-axis is pushed out to above 60 days.

I can either:

Remove this restriction but take China off the default selection list to remedy the bunching

or

keep the restriction but put a note below the graphs.

What do you think would be the better option?

The data is coming from JHU there may be inconsistencies. If you can pin point some specific issues I can look into them.

My main priority at the moment is getting region and metro based breakdowns on each individual country page as this should be very useful for people in those countries as opposed to the macro level graph at the top of the page.

thanks for your feedback

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by carlaiau** [comment]
@klartext China's max days are now set to 36 days, and the reasons for this are explained below the graph.
